### ISSUE TITLE
HELP setting up goimapnotify

### ISSUE THREAD

**Issue by atanasj** [licht1stein/context-transient.el#2]
Hi. I am reaching out in response to your article about `goimapnotify` on MacOS here: https://blaster.ai/blog/posts/goimapnotify-setup-for-mac.html

I am having trouble, I think setting up the environment variables correctly and was hoping for some advice, as you stated in your article:

> The most tricky part that took a good hour to debug was figuring out that you need to provide the PATH variable to the running process, as it doesn't have access to the system wide one. Until I did, goimapnotify would start and connect normally, and once the new email hit I got an error on the mbsync step.

I'm not a programmer, so excuse what might be a silly question, but how did determine that `PATH` variables that were needed?

**Comment by licht1stein** [comment]
Hi! This way of setting it up is more involved, so kudos for trying!

Now to your question. The `PATH` variable is just a list of directories where the shell looks for executables. 

The simplest way to get its contents to put into the plists is to run `echo $PATH` in the terminal and copy the output. 

Let me know if you need more help.

**Comment by atanasj** [comment]
Thanks for that. I'm having trouble setting up the path variables I think. `goimapnotify` uses `sh` by default, and not `zsh`. How did you figure out and configure your path correctly on the `plist`?

**Comment by licht1stein** [comment]
This is the part where you set it, reference the article:

<img width="753" alt="image" src="https://github.com/licht1stein/context-transient.el/assets/35418634/f743c6b7-6482-4d7c-bc84-1670c847b538">

**Comment by atanasj** [comment]
Thanks. I finally got it working!
